services:
  app:
    build:
      context: ../
      dockerfile: docker/dockerfile-app
    container_name: manga-base-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=manga_base_db
      - DB_USER=root
      - DB_PASSWORD=secret
    networks:
      - manga-network

  db:
    build:
      context: ../
      dockerfile: docker/dockerfile-banco
    container_name: manga-db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - manga-network

volumes:
  db-data:

networks:
  manga-network:
